trigger:
  - main # ou la branche de votre choix

jobs:
- job: TestKeyVaultAccess
  pool:
    vmImage: 'ubuntu-latest' # ou un autre agent de votre choix
  steps:
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'AzureKeyVaultConnection' 
      KeyVaultName: 'KeyVaultPremierProjet' 
      SecretsFilter: '*' 
      RunAsPreJob: false
