# azure-pipelines.yml

trigger:
- main 

pool:
  name: 'Agent'  

variables:
  keyVaultName: 'KeyVaultPremierProjet'
  secretName: 'MotDePasseVM1'
  serviceConnection: 'AzureKeyVaultConnection'

jobs:
- job: TestKeyVaultAccess
  displayName: 'Test Access to Key Vault'
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(serviceConnection)  # Utilisation de la connexion de service configurée dans Azure DevOps
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "Starting Azure CLI script to test Key Vault access"
        
        # Affichage des informations de connexion pour debugging
        echo "Attempting to login with Azure CLI"
        
        # Vérifie si le login est effectué correctement
        az account show
        
        if [ $? -ne 0 ]; then
          echo "Azure CLI login failed."
          exit 1
        fi

        echo "Logged in successfully. Now testing access to Key Vault: $keyVaultName"
        
        # Tester l'accès au Key Vault
        secret=$(az keyvault secret show --name $secretName --vault-name $keyVaultName --query value -o tsv)
        
        if [ $? -eq 0 ]; then
          echo "Successfully accessed the secret: $secret"
        else
          echo "Failed to access the secret."
          exit 1
        fi
