# azure-pipelines.yml

trigger:
- main # Remplace par la branche que tu veux déclencher

pool:
  name: 'Azure Pipelines' # Assure-toi que le pool d'agents auto-hébergés est spécifié ici

variables:
  keyVaultName: 'KeyVaultPremierProjet'
  secretName: 'MotDePasseVM1'
  serviceConnection: 'AzureKeyVaultConnection'

jobs:
- job: TestKeyVaultAccess
  displayName: 'Test Access to Key Vault'
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(serviceConnection)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "Testing access to Key Vault: $keyVaultName"
        secret=$(az keyvault secret show --name $secretName --vault-name $keyVaultName --query value -o tsv)
        
        if [ $? -eq 0 ]; then
          echo "Successfully accessed the secret: $secret"
        else
          echo "Failed to access the secret."
          exit 1
        fi
