jobs:
- job: TestKeyVaultAccess
  pool:
    name: Agent
  steps:
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'AzureKeyVaultConnection'
      KeyVaultName: 'KeyVaultPremierProjet'
      SecretsFilter: '*'
      RunAsPreJob: false
