trigger:
  - main

jobs:
- job: TestKeyVaultAccess
  pool:
    name: 'Azure Pipelines' 
  steps:
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'AzureKeyVaultConnection'
      KeyVaultName: 'KeyVaultPremierProjet' 
      SecretsFilter: '*'
      RunAsPreJob: false
