jobs:
- job: TestKeyVaultAccess
  pool:
    name: Azure Pipelines  # Spécifiez le nom du pool ici
  steps:
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'AzureKeyVaultConnection'
      KeyVaultName: 'KeyVaultPremierProjet'
      SecretsFilter: '*'
      RunAsPreJob: false
