# azure-pipelines.yml

trigger:
- main 

pool:
  name: 'Agent'  

variables:
  keyVaultName: 'KeyVaultPremierProjet'
  secretName: 'MotDePasseVM1'
  serviceConnection: 'AzureKeyVaultConnection'

jobs:
- job: TestKeyVaultAccess
  displayName: 'Test Access to Key Vault'
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(serviceConnection)  # Utilisation de la connexion de service configurée dans Azure DevOps
      scriptType: 'pscore'  # Utilise PowerShell Core à la place de Bash
      scriptLocation: 'inlineScript'
      inlineScript: |
        Write-Host "Starting Azure CLI script to test Key Vault access"
        
        # Affichage des informations de connexion pour debugging
        Write-Host "Attempting to login with Azure CLI"
        
        # Vérifie si le login est effectué correctement
        az account show
        
        if ($?) {
          Write-Host "Logged in successfully. Now testing access to Key Vault: $keyVaultName"
          
          # Tester l'accès au Key Vault
          $secret = az keyvault secret show --name $secretName --vault-name $keyVaultName --query value -o tsv
          
          if ($?) {
            Write-Host "Successfully accessed the secret: $secret"
          } else {
            Write-Host "Failed to access the secret."
            exit 1
          }
        } else {
          Write-Host "Azure CLI login failed."
          exit 1
        }
