trigger:
  branches:
    include:
      - main  # Exécuter le pipeline à chaque commit sur la branche principale

stages:
- stage: CompileAndValidate
  jobs:
    - job: ARMTemplateValidation
      displayName: "Compilation et validation du template ARM"
      pool:
        name: 'Azure Pipelines'
      steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'AzureKeyVaultConnection' 
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              # Valider le template ARM
              az deployment group validate \
                --resource-group 8CLD201_Devoir1_Infra \
                --template-file azuredeploy.json \
                --parameters azuredeploy.parameters.json

- stage: DeployToAzure
  jobs:
    - job: DeployARMTemplate
      displayName: "Déploiement du Template ARM dans Azure"
      pool:
        vmImage: 'ubuntu-latest'  # Utiliser un agent Ubuntu pour ce job
      steps:
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'AzureKeyVaultConnection'  # Utilisez votre connexion de service Azure
            subscriptionId: '3f8680cf-25db-4731-b00a-e524d785d205' 
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'KeyVaultGroup'  # Nom du groupe de ressources
            location: 'Canada Central'  # Choisissez la région appropriée
            templateLocation: 'Linked artifact'  # Utiliser un template lié
            csmFile: 'azuredeploy.json'  # Le fichier template
            csmParametersFile: 'azuredeploy.parameters.json'  # Fichier de paramètres
