trigger:
  branches:
    include:
      - main  # Branche principale

stages:
- stage: DeployToAzure
  jobs:
    - job: DeployARMTemplate
      displayName: "Déploiement du Template ARM dans Azure"
      pool:
        name: 'Agent'  # Agent auto-hébergé
      steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'AzureKeyVaultConnection'  # Connexion de service Azure
            scriptType: 'bash'  # Utilisation de bash
            scriptLocation: 'inlineScript'  # Utilisation de script en ligne
            inlineScript: |
              # Exécution de la validation du template ARM
              az deployment group validate \
                --resource-group 8CLD201_Devoir1_Infra \
                --template-file azuredeploy.json \
                --parameters azuredeploy.parameters.json

              # Déploiement du template
              az deployment group create \
                --resource-group 8CLD201_Devoir1_Infra \
                --template-file azuredeploy.json \
                --parameters azuredeploy.parameters.json
