trigger:
  branches:
    include:
      - main  # Exécuter le pipeline à chaque commit sur la branche principale

stages:
- stage: CompileAndValidate
  jobs:
    - job: ARMTemplateValidation
      displayName: "Compilation et validation du template ARM"
      pool:
        name: 'Agent'  # Utiliser l'agent Azure Pipelines par défaut
      steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'AzureKeyVaultConnection'  # Connexion au service Azure
            scriptType: 'pscore'  # Utiliser PowerShell Core
            scriptLocation: 'inlineScript'
            inlineScript: |
              # Validation du template ARM
              az deployment group validate `
                --resource-group KeyVaultGroup `
                --template-file azuredeploy.json `
                --parameters azuredeploy.parameters.json

- stage: DeployToAzure
  jobs:
    - job: DeployARMTemplate
      displayName: "Déploiement du Template ARM dans Azure"
      pool:
        vmImage: 'ubuntu-latest'  # Utiliser un agent Ubuntu pour ce job
      steps:
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'AzureKeyVaultConnection'  # Connexion Azure DevOps
            subscriptionId: '3f8680cf-25db-4731-b00a-e524d785d205'  # ID de l'abonnement Azure
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'KeyVaultGroup'  # Nom du groupe de ressources
            location: 'Canada Central'  # Région Azure
            templateLocation: 'Linked artifact'
            csmFile: 'azuredeploy.json'  # Chemin vers le fichier template ARM
            csmParametersFile: 'azuredeploy.parameters.json'  # Chemin vers le fichier des paramètres
