trigger:
  branches:
    include:
      - main

stages:
- stage: CompileAndValidate
  jobs:
    - job: ARMTemplateValidation
      displayName: "Compilation et validation du template ARM"
      pool:
        name: 'Agent'  # Utiliser l'agent auto-hébergé Windows
      steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'AzureKeyVaultConnection' 
            scriptType: 'pscore'  # Utiliser PowerShell Core
            scriptLocation: 'inlineScript'
            inlineScript: |
              # Validation du template ARM avec PowerShell
              az deployment group validate `
                --resource-group 8CLD201_Devoir1_Infra `
                --template-file azuredeploy.json `
                --parameters azuredeploy.parameters.json
              
- stage: DeployToAzure
  jobs:
    - job: DeployARMTemplate
      displayName: "Déploiement du Template ARM dans Azure"
      pool:
        vmImage: 'ubuntu-latest'  # Utiliser un agent Ubuntu pour ce job
      steps:
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'AzureKeyVaultConnection'
            subscriptionId: '3f8680cf-25db-4731-b00a-e524d785d205'
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'KeyVaultGroup'
            location: 'Canada Central'
            templateLocation: 'Linked artifact'
            csmFile: 'azuredeploy.json'
            csmParametersFile: 'azuredeploy.parameters.json'
