trigger:
  branches:
    include:
      - main  # Exécuter le pipeline à chaque commit sur la branche principale

stages:
- stage: CompileAndValidate
  jobs:
    - job: ARMTemplateValidation
      displayName: "Compilation et validation du template ARM"
      pool:
        name: 'Azure Pipelines'
      steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'AzureKeyVaultConnection'  # Utilisation de votre connexion de service
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az deployment group validate \
                --resource-group 8CLD201_Devoir1_Infra \
                --template-file azuredeploy.json \
                --parameters azuredeploy.parameters.json

- stage: DeployToAzure
  jobs:
    - job: DeployARMTemplate
      displayName: "Déploiement du Template ARM dans Azure"
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'AzureKeyVaultConnection'  # Utilisation de votre connexion de service
            subscriptionId: '375be4f5-a251-4fb2-8f5a-13d6f5a2cedf'
            action: 'Create Or Update Resource Group'
            resourceGroupName: '8CLD201_Devoir1_Infra'
            location: 'Canada Central'
            templateLocation: 'Linked artifact'
            csmFile: 'azuredeploy.json'
            csmParametersFile: 'azuredeploy.parameters.json'
