# Déclenchement automatique sur la branche principale
trigger:
  branches:
    include:
      - main

pool:
  name: 'Agent'  # Nom de l'agent auto-hébergé utilisé pour exécuter les tâches du pipeline

variables:
  keyVaultName: 'KeyVaultPremierProjet'
  azureSubscription: 'AzureKeyVaultConnection'
  resourceGroupName: 'vm-loadbalancer-rg'
  location: 'Canada Central'
  templateFile: 'templates/deployment-template.json'
  parametersFile: 'templates/deployment-parameters.json'

stages:
  - stage: DeployInfrastructure
    displayName: "Déployer l'infrastructure Azure"
    jobs:
      - job: DeployResources
        displayName: "Déployer les VMs et Load Balancer"
        steps:
          - checkout: self

          # Étape de récupération des secrets depuis le Key Vault
          - task: AzureKeyVault@2
            inputs:
              azureSubscription: $(azureSubscription)
              KeyVaultName: $(keyVaultName)
              SecretsFilter: 'adminPassword,MotDePasseVM1,MotDePasseVM2'

          # Diagnostic de récupération des mots de passe en utilisant Bash explicitement
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                echo "Vérification de la récupération des mots de passe"
                if [ -z "$adminPassword" ]; then
                  echo "Erreur : adminPassword n'a pas été récupéré correctement."
                  exit 1
                fi
                if [ -z "$MotDePasseVM1" ]; then
                  echo "Erreur : MotDePasseVM1 n'a pas été récupéré correctement."
                  exit 1
                fi
                if [ -z "$MotDePasseVM2" ]; then
                  echo "Erreur : MotDePasseVM2 n'a pas été récupéré correctement."
                  exit 1
                fi
                echo "Tous les mots de passe ont été récupérés avec succès."

          # Déploiement des ressources
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Création du groupe de ressources $(resourceGroupName)"
                az group create --name $(resourceGroupName) --location $(location)

                echo "Déploiement des machines virtuelles et du Load Balancer"
                az deployment group create \
                  --resource-group $(resourceGroupName) \
                  --template-file $(templateFile) \
                  --parameters @$(parametersFile) \
                  --parameters adminPassword="$(adminPassword)"
            displayName: "Déployer les VMs et le Load Balancer"
