trigger:
  branches:
    include:
      - main

stages:
- stage: CompileAndValidate
  jobs:
    - job: ARMTemplateValidation
      displayName: "Compilation et validation du template ARM"
      pool:
        name: 'Agent'  # Utiliser l'agent auto-hébergé nommé "Agent"
      steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'AzureKeyVaultConnection'  # Nom de la connexion de service Azure
            scriptType: 'pscore'  # Utiliser PowerShell Core
            scriptLocation: 'inlineScript'
            inlineScript: |
              # Validation du template ARM avec PowerShell
              az deployment group validate `
                --resource-group 8CLD201_Devoir1 `
                --template-file azuredeploy.json `
                --parameters azuredeploy.parameters.json
              
- stage: DeployToAzure
  jobs:
    - job: DeployARMTemplate
      displayName: "Déploiement du Template ARM dans Azure"
      pool:
        vmImage: 'ubuntu-latest'  # Utiliser un agent Ubuntu pour ce job
      steps:
        - task: AzureKeyVault@2
          inputs:
            azureSubscription: 'AzureKeyVaultConnection'  # Connexion Azure avec le service principal configuré
            KeyVaultName: 'Devoir1Key'  # Nom du KeyVault
            SecretsFilter: 'Secret1,Secret2'  # Récupérer les secrets "Secret1" et "Secret2"
          
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'AzureKeyVaultConnection'  # Connexion Azure avec le service principal configuré
            subscriptionId: '3f8680cf-25db-4731-b00a-e524d785d205'  # ID de l'abonnement Azure
            action: 'Create Or Update Resource Group'
            resourceGroupName: '8CLD201_Devoir1'  # Nom du groupe de ressources
            location: 'Canada Central'
            templateLocation: 'Linked artifact'
            csmFile: 'azuredeploy.json'  # Chemin du fichier template ARM
            csmParametersFile: 'azuredeploy.parameters.json'  # Chemin du fichier paramètres du template ARM
