trigger:
  branches:
    include:
      - main

pool:
  name: 'Agent' # Nom de l'agent auto-hébergé utilisé pour exécuter les tâches du pipeline

# Déclaration des variables globales
variables:
  keyVaultName: 'KeyVaultPremierProjet'  # Nom du Key Vault où sont stockés les mots de passe
  azureSubscription: 'AzureKeyVaultConnection'  # Connexion de service Azure
  resourceGroupName: 'vm-loadbalancer-rg'  # Nom du groupe de ressources
  location: 'Central Canada'  # Région Azure
  templateFile: 'templates/deployment-template.json'  # Chemin du fichier de template ARM
  parametersFile: 'templates/deployment-parameters.json'  # Chemin du fichier des paramètres ARM

# Étape de déploiement des ressources dans Azure
stages:
  - stage: DeployInfrastructure
    displayName: "Déployer l'infrastructure Azure"
    jobs:
      - job: DeployResources
        displayName: "Déployer les VMs et Load Balancer"
        steps:
          # Étape 1 : Récupérer les fichiers depuis le dépôt GitHub
          - checkout: self

          # Étape 2 : Récupération du mot de passe administrateur depuis le Key Vault
          - task: AzureKeyVault@2
            inputs:
              azureSubscription: $(azureSubscription)
              KeyVaultName: $(keyVaultName)
              SecretsFilter: 'adminPassword'  # Le secret adminPassword doit être défini dans le Key Vault
              RunAsPreJob: true  # Le mot de passe sera disponible pour les étapes suivantes

          # Étape 3 : Créer le groupe de ressources et déployer les ressources avec Azure CLI
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Création du groupe de ressources $(resourceGroupName)"
                az group create --name $(resourceGroupName) --location $(location)

                echo "Déploiement des machines virtuelles et du Load Balancer"
                az deployment group create \
                  --resource-group $(resourceGroupName) \
                  --template-file $(templateFile) \
                  --parameters @$(parametersFile) \
                  --parameters adminPassword="$(adminPassword)"
            displayName: "Déployer les VMs et le Load Balancer"
