trigger:
  branches:
    include:
      - main

pool:
  name: 'Agent'  # Utilisation de ton agent auto-hébergé

stages:
- stage: CompileAndValidate
  jobs:
    - job: ARMTemplateValidation
      displayName: "Compilation et validation du template ARM"
      pool:
        name: 'Agent'  # Utilisation de l'agent auto-hébergé
      steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'ServiceConnection'  # Utilisation de la nouvelle connexion de service
            scriptType: 'pscore'  # Utiliser PowerShell Core
            scriptLocation: 'inlineScript'
            inlineScript: |
              # Validation du template ARM avec PowerShell
              az deployment group validate 
                --resource-group 8CLD201_Devoir1 
                --template-file azuredeploy.json 
                --parameters azuredeploy.parameters.json
              
- stage: DeployToAzure
  jobs:
    - job: DeployARMTemplate
      displayName: "Déploiement du Template ARM dans Azure"
      pool:
        name: 'Agent'  # Utilisation de l'agent auto-hébergé
      steps:
        - task: AzureKeyVault@2
          inputs:
            azureSubscription: 'ServiceConnection'  # Utilisation de la connexion de service
            KeyVaultName: 'CoffreDevoir1'  # Nom de ton KeyVault
            SecretsFilter: '*'  # Filtrer tous les secrets (Secret1, Secret2)
          
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'ServiceConnection'  # Connexion de service
            subscriptionId: '3f8680cf-25db-4731-b00a-e524d785d205'  # ID de la souscription Azure
            action: 'Create Or Update Resource Group'
            resourceGroupName: '8CLD201_Devoir1'
            location: 'Canada Central'
            templateLocation: 'Linked artifact'
            csmFile: 'azuredeploy.json'  # Chemin du fichier template ARM
            csmParametersFile: 'azuredeploy.parameters.json'  # Chemin du fichier paramètres du template ARM